import { describe, it, expect, beforeAll, vi } from 'vitest'

process.env.MISSION_CONTROL_TEST_MODE = '1'

vi.mock('@/lib/config', () => ({
  config: { dbPath: ':memory:', memoryDir: '', memoryAllowedPrefixes: [] },
  ensureDirExists: vi.fn(),
}))
vi.mock('@/lib/auto-credentials', () => ({
  ensureAutoGeneratedCredentials: vi.fn(),
}))

import { getDatabase } from '@/lib/db'
import { createSkill, updateSkill, recordSkillRun } from '@/lib/skills/db'
import { ingestText } from '@/lib/skills/ingest'
import { recommendSkills } from '@/lib/memory/skill-recommender'
import { retrieveContext, logContextRetrieval } from '@/lib/memory/retriever'
import { getBrandVoice, setBrandVoice, getUserProfile, setUserProfile, buildMemoryContext } from '@/lib/memory/brand-voice'
import { buildSessionNote } from '@/lib/memory/writer'

const WS = 1

beforeAll(() => {
  getDatabase() // run migrations
  // Seed 3 agents so council can start.
  const db = getDatabase()
  const ins = db.prepare(`INSERT OR IGNORE INTO agents (name, role, status, workspace_id) VALUES (?, 'developer', 'idle', 1)`)
  for (const n of ['Ares', 'Vega', 'Sol']) ins.run(n)
})

describe('Memory loop — skill recommender', () => {
  it('returns empty list when no active skills', () => {
    const recs = recommendSkills(WS, 'do something with SEO')
    expect(Array.isArray(recs)).toBe(true)
  })

  it('scores skills by relevance to the goal', () => {
    const s1 = createSkill({ workspaceId: WS, name: 'SEO Strategist', status: 'active', description: 'keyword research and search intent analysis' })
    const s2 = createSkill({ workspaceId: WS, name: 'Budget Planner', status: 'active', description: 'financial planning and cost analysis' })

    const recs = recommendSkills(WS, 'keyword SEO strategy for my website', 5)
    expect(recs.length).toBeGreaterThan(0)
    const seoRec = recs.find(r => r.skill.id === s1.id)
    const budgetRec = recs.find(r => r.skill.id === s2.id)
    if (seoRec && budgetRec) {
      expect(seoRec.relevanceScore).toBeGreaterThan(budgetRec.relevanceScore)
    }
  })

  it('weights historical success scores into the combined score', () => {
    const skill = createSkill({ workspaceId: WS, name: 'High Success Skill', status: 'active', description: 'content marketing strategy' })
    recordSkillRun({ skillId: skill.id, successScore: 0.95 })
    recordSkillRun({ skillId: skill.id, successScore: 0.90 })

    const recs = recommendSkills(WS, 'content marketing strategy for blog', 10)
    const found = recs.find(r => r.skill.id === skill.id)
    expect(found).toBeDefined()
    expect(found!.successScore).toBeCloseTo(0.925, 2)
    // combined = relevance * 0.6 + success * 0.4
    expect(found!.combinedScore).toBeGreaterThan(0.3)
  })
})

describe('Memory loop — brand voice + profile', () => {
  it('returns starter template when nothing is set', async () => {
    const bv = await getBrandVoice(99) // unused workspace
    expect(bv).toContain('Brand Voice')
    const pr = await getUserProfile(99)
    expect(pr).toContain('Profile')
  })

  it('saves and retrieves brand voice from DB when vault is not configured', async () => {
    await setBrandVoice(WS, '# Brand Voice\n\n## Tone\nDirect and confident.')
    const loaded = await getBrandVoice(WS)
    expect(loaded).toContain('Direct and confident.')
  })

  it('saves and retrieves user profile', async () => {
    await setUserProfile(WS, '# Profile\n\n## About me\nI run an SEO agency.')
    const loaded = await getUserProfile(WS)
    expect(loaded).toContain('SEO agency')
  })

  it('buildMemoryContext strips headings and produces an injectable block', async () => {
    await setBrandVoice(WS, '# Brand Voice\n\n## Tone\nShort sentences. No jargon.')
    await setUserProfile(WS, '# Profile\n\n## About me\nDigital marketing consultant.')
    const ctx = await buildMemoryContext(WS)
    expect(ctx).toContain('Short sentences')
    expect(ctx).toContain('Digital marketing consultant')
    // Headings stripped
    expect(ctx).not.toContain('# Brand Voice')
  })
})

describe('Memory loop — context retrieval', () => {
  it('returns a context block and skill recommendations', async () => {
    await ingestText(WS, 'Local SEO Guide', 'Local SEO requires Google Business Profile optimisation. You must claim and verify your listing. Always respond to reviews. Include local keywords in your title tag.')
    await setBrandVoice(WS, '# Brand Voice\n\n## Tone\nProfessional and helpful.')

    const result = await retrieveContext(WS, 'help me with local SEO')
    expect(typeof result.contextBlock).toBe('string')
    expect(result.snippets.length).toBeGreaterThan(0)
    expect(Array.isArray(result.recommendedSkills)).toBe(true)
    // Brand voice should always be present.
    const bvSnippet = result.snippets.find(s => s.sourceType === 'brand_voice')
    expect(bvSnippet).toBeDefined()
  })

  it('logs retrieved snippets to memory_context_log', async () => {
    const db = getDatabase()
    const session = db.prepare(
      `INSERT INTO council_sessions (workspace_id, title, user_goal, status) VALUES (1, 'T', 'G', 'debating') RETURNING id`
    ).get() as { id: number }

    const result = await retrieveContext(WS, 'SEO content strategy')
    const { logContextRetrieval } = await import('@/lib/memory/retriever')
    logContextRetrieval(session.id, result)

    const rows = db.prepare(`SELECT * FROM memory_context_log WHERE council_session_id = ?`).all(session.id)
    expect(rows.length).toBeGreaterThan(0)
  })
})

describe('Memory loop — session write-back', () => {
  it('buildSessionNote produces valid markdown with wiki links', () => {
    const note = buildSessionNote({
      sessionId: 42,
      workspaceId: WS,
      title: 'SEO Sprint Planning',
      goal: 'Rank for "emergency plumber Dallas"',
      consensus: 'Target commercial-intent keywords with service pages.',
      roundCount: 3,
      taskCount: 5,
      skillsUsed: ['SEO Strategist', 'Content Brief Writer'],
    })
    expect(note).toContain('SEO Sprint Planning')
    expect(note).toContain('emergency plumber Dallas')
    expect(note).toContain('[[SEO Strategist]]')
    expect(note).toContain('session_id: 42')
    expect(note).toContain('[[Brand Voice]]')
  })
})
