import { describe, it, expect, beforeAll, vi } from 'vitest'

/**
 * End-to-end Agent Council test against a REAL in-memory SQLite database.
 * Exercises migration 051, agent selection, debate rounds, voting,
 * consensus evaluation, and conversion to Mission Control tasks.
 */

process.env.MISSION_CONTROL_TEST_MODE = '1'

// A single in-memory DB shared across the run (:memory: is per-connection).
vi.mock('@/lib/config', () => ({
  config: { dbPath: ':memory:' },
  ensureDirExists: vi.fn(),
}))
vi.mock('@/lib/auto-credentials', () => ({
  ensureAutoGeneratedCredentials: vi.fn(),
}))

import { getDatabase } from '@/lib/db'
import {
  startCouncil,
  runDebateRound,
  advanceCouncil,
  executeCouncilStrategy,
} from '@/lib/council/engine'
import { getCouncilSessionDetail } from '@/lib/council/db'

beforeAll(() => {
  const db = getDatabase() // runs all migrations incl. 051_council_mode
  // Seed five online agents in workspace 1.
  const insert = db.prepare(
    `INSERT INTO agents (name, role, status, workspace_id) VALUES (?, ?, 'idle', 1)`
  )
  for (const name of ['Aegis', 'Scout', 'Vega', 'Atlas', 'Nova']) {
    insert.run(name, 'developer')
  }
})

describe('Agent Council — schema', () => {
  it('creates all four council tables', () => {
    const db = getDatabase()
    const tables = db
      .prepare(
        `SELECT name FROM sqlite_master WHERE type='table'
         AND name IN ('council_sessions','council_participants',
           'council_messages','council_votes')`
      )
      .all()
      .map((r: any) => r.name)
      .sort()
    expect(tables).toEqual([
      'council_messages',
      'council_participants',
      'council_sessions',
      'council_votes',
    ])
  })
})

describe('Agent Council — full deliberation flow', () => {
  it('runs goal → debate → consensus → execution', async () => {
    // A. Start council — selects agents, assigns roles, runs round 1.
    const { session, participants } = await startCouncil({
      workspaceId: 1,
      title: 'SEO strategy',
      userGoal: 'Use this keyword to create an SEO strategy.',
    })
    expect(participants.length).toBeGreaterThanOrEqual(3)
    expect(participants.length).toBeLessThanOrEqual(5)
    expect(participants[0].council_role).toBe('Strategist')
    expect(session.current_round).toBe(1)
    expect(session.status).toBe('debating')

    // C–E. Run challenge + revision rounds.
    await runDebateRound(session.id) // round 2
    await runDebateRound(session.id) // round 3

    let detail = getCouncilSessionDetail(session.id, 1)!
    expect(detail.session.current_round).toBe(3)
    // Every participant speaks each round.
    expect(detail.messages.length).toBe(participants.length * 3)
    expect(detail.messages.some((m) => m.message_type === 'challenge')).toBe(true)

    // F–G. Collect votes and evaluate consensus.
    const { session: voted, consensus } = await advanceCouncil(session.id)
    expect(consensus.votes.length).toBe(participants.length)
    expect(consensus.agreeFraction).toBeGreaterThan(0)
    expect(['consensus_reached', 'debating']).toContain(voted.status)

    // Drive to a terminal state if more rounds are needed.
    let guard = 0
    let current = voted
    while (current.status === 'debating' && guard < 10) {
      if (current.current_round < current.max_rounds) {
        await runDebateRound(session.id)
      }
      current = (await advanceCouncil(session.id)).session
      guard++
    }
    expect(['consensus_reached', 'failed']).toContain(current.status)
  })

  it('converts a consensus strategy into Mission Control tasks', async () => {
    const { session } = await startCouncil({
      workspaceId: 1,
      title: 'Launch checklist',
      userGoal: 'Plan a product launch.',
    })

    // Run rounds + votes until consensus is reached.
    let detail = getCouncilSessionDetail(session.id, 1)!
    let guard = 0
    while (detail.session.status !== 'consensus_reached' && guard < 12) {
      if (
        detail.session.status === 'failed' ||
        detail.session.status === 'executed'
      ) {
        break
      }
      if (detail.session.current_round < detail.session.max_rounds) {
        await runDebateRound(session.id)
      }
      await advanceCouncil(session.id)
      detail = getCouncilSessionDetail(session.id, 1)!
      guard++
    }

    if (detail.session.status === 'consensus_reached') {
      const db = getDatabase()
      const before = (
        db.prepare(`SELECT COUNT(*) c FROM tasks`).get() as any
      ).c
      const { taskIds, output } = executeCouncilStrategy(session.id)
      const after = (
        db.prepare(`SELECT COUNT(*) c FROM tasks`).get() as any
      ).c

      expect(taskIds.length).toBeGreaterThan(0)
      expect(after - before).toBe(taskIds.length)
      expect(output.execution_tasks.length).toBe(taskIds.length)
      expect(output.confidence).toBeGreaterThan(0)

      // Tasks are tagged back to the council session.
      const task = db
        .prepare(`SELECT metadata FROM tasks WHERE id = ?`)
        .get(taskIds[0]) as any
      expect(JSON.parse(task.metadata).council_session_id).toBe(session.id)
      expect(getCouncilSessionDetail(session.id, 1)!.session.status).toBe(
        'executed'
      )
    }
  })
})
