import { describe, it, expect, beforeAll, vi } from 'vitest'

/**
 * End-to-end Skill Engine test against a REAL in-memory SQLite database.
 * Exercises migration 052, skill CRUD + versioning, knowledge ingestion
 * (chunking + digest + FTS), skill generation from a source, the slash
 * command parser, and the Council Mode bridge.
 */

process.env.MISSION_CONTROL_TEST_MODE = '1'

vi.mock('@/lib/config', () => ({
  config: { dbPath: ':memory:' },
  ensureDirExists: vi.fn(),
}))
vi.mock('@/lib/auto-credentials', () => ({
  ensureAutoGeneratedCredentials: vi.fn(),
}))

import { getDatabase } from '@/lib/db'
import {
  createSkill,
  getSkillDetail,
  updateSkill,
  archiveSkill,
  listSkills,
  searchKnowledge,
  attachSkillsToCouncil,
  getCouncilSkills,
  recordSkillRun,
  getSkillStats,
  slugify,
} from '@/lib/skills/db'
import { chunkText, htmlToText, ingestText } from '@/lib/skills/ingest'
import { buildSkillFromSource } from '@/lib/skills/skill-builder'
import { parseCommand, isParseError } from '@/lib/skills/commands'

const WS = 1

const SAMPLE = `SEO Auditing Procedure

This guide explains the audit process. You must always start with keyword intent.

1. Identify the primary keyword and its search intent.
2. Review the page title and H1 for the keyword.
3. Check internal links and schema markup.

Warning: never keyword-stuff the title tag. Avoid thin content.

For example, a service page should target a commercial-intent keyword.
A technical audit must check crawlability and Core Web Vitals.`

beforeAll(() => {
  const db = getDatabase() // runs all migrations incl. 052_skill_engine
  const insert = db.prepare(
    `INSERT INTO agents (name, role, status, workspace_id) VALUES (?, ?, 'idle', 1)`
  )
  for (const name of ['Aegis', 'Scout', 'Vega']) insert.run(name, 'developer')
})

describe('Skill Engine — schema', () => {
  it('creates all skill engine tables', () => {
    const db = getDatabase()
    const tables = db
      .prepare(
        `SELECT name FROM sqlite_master WHERE type='table'
         AND name IN ('agent_skills','agent_skill_versions',
           'knowledge_sources','knowledge_chunks','agent_skill_runs',
           'council_session_skills','knowledge_chunks_fts')`
      )
      .all()
      .map((r: any) => r.name)
    expect(tables).toHaveLength(7)
  })

  it('seeds the built-in Skill Builder agent', () => {
    const db = getDatabase()
    const agent = db
      .prepare(`SELECT * FROM agents WHERE role = 'skill-builder'`)
      .get() as any
    expect(agent?.name).toBe('Skill Builder')
  })
})

describe('Skill Engine — skills CRUD + versioning', () => {
  it('creates a skill with a slug and an initial version', () => {
    const skill = createSkill({
      workspaceId: WS,
      name: 'SEO Strategist',
      instructions: 'Initial procedure.',
    })
    expect(skill.slug).toBe('seo-strategist')
    const detail = getSkillDetail(skill.id, WS)!
    expect(detail.versions).toHaveLength(1)
    expect(detail.versions[0].version_number).toBe(1)
  })

  it('records a new version when instructions change', () => {
    const skill = createSkill({ workspaceId: WS, name: 'Proposal Writer' })
    updateSkill(skill.id, { instructions: 'v2 procedure', status: 'active' })
    const detail = getSkillDetail(skill.id, WS)!
    expect(detail.versions).toHaveLength(2)
    expect(detail.status).toBe('active')
  })

  it('archives a skill and keeps slugs unique', () => {
    const a = createSkill({ workspaceId: WS, name: 'Duplicate Name' })
    const b = createSkill({ workspaceId: WS, name: 'Duplicate Name' })
    expect(a.slug).not.toBe(b.slug)
    archiveSkill(a.id)
    expect(getSkillDetail(a.id, WS)!.status).toBe('archived')
    expect(listSkills(WS, 'archived').some((s) => s.id === a.id)).toBe(true)
  })
})

describe('Skill Engine — ingestion', () => {
  it('chunks text into non-empty pieces', () => {
    const chunks = chunkText(SAMPLE, 120)
    expect(chunks.length).toBeGreaterThan(1)
    expect(chunks.every((c) => c.length > 0)).toBe(true)
  })

  it('cleans HTML down to readable text', () => {
    const { title, text } = htmlToText(
      '<html><head><title>Hi</title><style>x{}</style></head>' +
        '<body><nav>menu</nav><p>Real content here.</p></body></html>'
    )
    expect(title).toBe('Hi')
    expect(text).toContain('Real content here.')
    expect(text).not.toContain('menu')
  })

  it('ingests text, stores a digest, and indexes for search', async () => {
    const result = await ingestText(WS, 'SEO Audit Guide', SAMPLE)
    expect(result.chunkCount).toBeGreaterThan(0)
    expect(result.source.summary).toBeTruthy()
    expect(result.suggestSkill).toBe(true) // has procedures + rules

    const hits = searchKnowledge('keyword intent')
    expect(hits.length).toBeGreaterThan(0)
    expect(hits[0].source_title).toBe('SEO Audit Guide')
  })
})

describe('Skill Engine — generate skill from source', () => {
  it('builds a structured skill document from a knowledge source', async () => {
    const ingested = await ingestText(WS, 'Epoxy Training', SAMPLE)
    const skill = await buildSkillFromSource({
      workspaceId: WS,
      sourceId: ingested.source.id,
      name: 'Epoxy Installer',
    })
    expect(skill.source_type).toBe('generated')
    expect(skill.instructions).toContain('Step-by-step procedure:')
    expect(skill.instructions).toContain('Quality checklist:')
  })
})

describe('Skill Engine — command parser', () => {
  it('parses skill, learn, and council commands', () => {
    expect(parseCommand('/skill create seo-auditor')).toMatchObject({
      kind: 'skill.create',
      name: 'seo-auditor',
    })
    expect(parseCommand('/skill list')).toMatchObject({ kind: 'skill.list' })
    expect(parseCommand('/learn link https://example.com')).toMatchObject({
      kind: 'learn.link',
      url: 'https://example.com',
    })
    expect(
      parseCommand('/skill create-from-source x from epoxy-guide')
    ).toMatchObject({ kind: 'skill.createFromSource', source: 'epoxy-guide' })
    expect(parseCommand('/use seo-auditor on rank my page')).toMatchObject({
      kind: 'use.skill',
      skill: 'seo-auditor',
      goal: 'rank my page',
    })
    expect(parseCommand('/council use a, b, c')).toMatchObject({
      kind: 'council.use',
      skills: ['a', 'b', 'c'],
    })
  })

  it('returns a parse error for unknown commands', () => {
    const r = parseCommand('/frobnicate now')
    expect(isParseError(r)).toBe(true)
  })
})

describe('Skill Engine — Council bridge + skill memory', () => {
  it('attaches skills to a council session', () => {
    const db = getDatabase()
    const session = db
      .prepare(
        `INSERT INTO council_sessions (workspace_id, title, user_goal, status)
         VALUES (1, 'Test', 'Goal', 'debating') RETURNING id`
      )
      .get() as { id: number }
    const skill = createSkill({ workspaceId: WS, name: 'Bridge Skill' })
    attachSkillsToCouncil(session.id, [{ skillId: skill.id }])
    const attached = getCouncilSkills(session.id)
    expect(attached).toHaveLength(1)
    expect(attached[0].skill_name).toBe('Bridge Skill')
  })

  it('records skill runs and aggregates success scores', () => {
    const skill = createSkill({ workspaceId: WS, name: 'Tracked Skill' })
    recordSkillRun({ skillId: skill.id, successScore: 0.8 })
    recordSkillRun({ skillId: skill.id, successScore: 0.6 })
    const stats = getSkillStats(skill.id)
    expect(stats.run_count).toBe(2)
    expect(stats.avg_success).toBeCloseTo(0.7)
  })

  it('slugify normalizes names', () => {
    expect(slugify('  Hello World!! ')).toBe('hello-world')
  })
})
